#Define Colours
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

#Players
PLAYER_X = 'X'
PLAYER_O = 'O'

#Display Settings
TILESIZE = 256
ROWS = 3
COLUMNS = 3
WIDTH = TILESIZE * COLUMNS
HEIGHT = TILESIZE * ROWS
TITLE = "Tic-Tac-Toe"
BG_COLOUR = BLACK
GRID_WIDTH = WIDTH / TILESIZE
GRID_HEIGHT = HEIGHT / TILESIZE