#Define Colours
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

#Display Settings
TILESIZE = 256
ROWS = 3
COLUMNS = 3
WIDTH = TILESIZE * COLUMNS
HEIGHT = TILESIZE * ROWS
FPS = 60
TITLE = "Tic-Tac-Toe"
BG_COLOUR = BLACK
GRID_WIDTH = WIDTH / TILESIZE
GRID_HEIGHT = HEIGHT / TILESIZE